version: "3.6"
services:
  postgres:
    image: postgres:11-alpine
  app:
    image: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py betterrun 0.0.0.0:8000"
